---
# file: plays/includes/playbook.yml
- name: Proxy Playbook
  hosts: ${hosts}

  # see if we can git rid of this using group_vars/all
  # not possible because group_vars/all is not preprocessed
  vars_files:
  - [ "${vars_files_global}", 'vars/global.yml' ]

  tasks:
  - include: ${playbook_tasks}/${playbook}.yml

  handlers:
  - include: ${playbook_handlers}/global.yml
