# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  vms = []
  vms.push ip: "10.0.2.11", label: "vm01", name: "vm01", box: "ubuntu/xenial64"
  #vms.push ip: "10.0.2.21", label: "vm02", name: "vm02", box: "ubuntu/xenial64"

  vms.each do |m|
    config.vm.define m[:label] do |s|

      s.vm.box = m[:box]

      s.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "1024"]
        v.name = m[:name]
      end

      s.vm.hostname = m[:name]
      s.vm.network :private_network, ip: m[:ip], netmask: "255.255.0.0"

      if m[:box].include? "ubuntu"
        s.vm.provision "shell" do |sh|
          ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

          sh.privileged = true
          sh.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            sudo sed -i 's/^#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
            sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            sudo sed -i 's/^GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
            sudo service ssh restart
          SHELL
        end
      end

    end
  end

end
