---
- import_playbook: ../includes/base.yml myhosts=vms
- import_playbook: ../includes/docker.yml myhosts=vms
#- import_playbook: ../includes/jenkins.yml hosts=vm01
- import_playbook: ../includes/kubernetes.yml myhosts=vms
