---
# file: roles/certbot/tasks/install_deb.yml
- name: certbot - Install dependencies
  package:
    name: software-properties-common
    state: latest
  tags: certbot

- name: certbot - Add apt repo
  apt_repository:
    repo: 'ppa:certbot/certbot'
    update_cache: yes
  tags: certbot

- name: certbot - Install Certbot
  package:
    name: certbot
    state: present
  tags: certbot


