---
# file: roles/docker/tasks/install_deb.yml
- name: docker - Add apt key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
  tags: docker

- name: docker - Add apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  tags: docker

- name: docker - Update apt
  apt: update_cache=yes

- name: docker - Install packages to allow apt to use a repository over HTTPS
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce
  tags: docker

- name: docker - Install Docker
  package:
    name: docker-ce
    state: present
  tags: docker
