---
# file: roles/base/tasks/bash.yml

- file:
    path: /usr/local/app
    state: directory
    owner: root
    group: root
  tags: bash

- git:
    repo: 'https://github.com/magicmonty/bash-git-prompt.git'
    dest: /usr/local/app/bash-git-prompt
    update: no
  tags: bash

- name: Insert/Update bash configuration
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      if [ -f "/usr/local/app/bash-git-prompt/gitprompt.sh" ]; then
          GIT_PROMPT_ONLY_IN_REPO=1
          source /usr/local/app/bash-git-prompt/gitprompt.sh
      fi
  tags: bash

  #- name: Update gitprompt
  #  replace:
  #    path: /usr/local/app/bash-git-prompt/gitprompt.sh
  #    regexp: 'PS1="\${NEW_PROMPT'
  #    replace: 'PS1="(\u@\h) ${NEW_PROMPT'
  #  tags: bash
