---
# file: roles/base/tasks/dotfiles.yml
- name: dotfiles - Install all
  copy:
    src: "default{{ item[1] }}"
    dest: "~{{ item[0].name }}/{{ item[1] }}"
    owner: "{{ item[0].name }}"
    group: "{{ item[0].name }}"
  with_nested:
    - "{{ users }}"
    - ['.curlrc', '.gitconfig', '.vimrc']
  when: users is not none
  tags: dotfiles

